{% set name = "hvac" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1b85e3320e8642dd82f234db63253cda169a817589e823713dc5fca83119b1e2

build:
  number: 0
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed

requirements:
  host:
    - python
    - pip
    - poetry-core >=1.0.0
  run:
    - python
    - requests >=2.27.1,<3.0.0
  # pyhcl is missing
  # run_constrained:
  #   - pyhcl >=0.4.4,<0.5.0

test:
  source_files:
    - tests
  imports:
    - hvac
    - hvac.api
    - hvac.api.auth_methods
    - hvac.api.secrets_engines
    - hvac.api.system_backend
    - hvac.constants
    - hvac.v1
  requires:
    - pip
    - pytest
    - parameterized
    - requests-mock
    - pytest-mock
    - werkzeug
    - flask
    - flask-sqlalchemy
  commands:
    - pip check
    # missing pyhcl and ldap*
    {% set ignore_tests = " --ignore=tests/integration_tests/api/" %}
    {% set ignore_tests = ignore_tests + " --ignore=tests/integration_tests/v1/" %}
    - pytest tests -v {{ ignore_tests }}

about:
  home: https://python-hvac.org/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: HashiCorp Vault API client
  description: |
    A HashiCorp Vault Python client is used to interact with a Vault server programmatically,
    allowing secure storage, retrieval, and management of secrets like API keys, passwords,
    and certificates. It enables authentication, secret fetching, dynamic secrets generation,
    and encryption operations within Python applications.
  doc_url: https://hvac.readthedocs.io/
  dev_url: https://github.com/hvac/hvac

extra:
  recipe-maintainers:
    - mariusvniekerk
