travis:
  secure:
    BINSTAR_TOKEN: cXYcshEH7BfgqHmmQuAalm0aotjU+gt2ZCAxVAFuGY4qRc/ATQf6bXAJIRR1Fid92pjQyoPfA/3XniL2rbaMYLjkGM1Q5sKJeh/rcliUXgQyJVb8O4IybfGgHI1cQ+b9Mas/1f9AR9QXzpLmNNoEEoIPi4KrBn3MQOnhMVBCRGqc+g9vqSG2WkwHca+aV0JGBLZXkpfoTChTsz7qtUx/3PQB9DXirOizx6014YtfaCnI+DOXc6oYBDOcmWqJ5lJqPq3E7knDLR0mk9D47Y6BuU3lCSlpuCnKMQYGtmxp2rOiqnpPhA09wK4hKFlEXJYG+oNwHftulry3ygvoz3DbAXLXAaWK6HKLBBz8PfM2FfFRAISiB/kFyEyLXMWilGI7zKD5JpcavNHv56reU9LtKcCsvoklgtaw2eu7H44fkymEScPw2jyGTB+pc8guwSLm/nmNagV/WZoKyvUDt3Efvqa53CysFTyavvliHBimr+u29HQausBE/0Hkp8Dy6O0GyyGfwjwalx/gY0b6W8TjQLCXj74UoL5Rxzk1VE874yRIDzbUDJVbc0f/oaVTWXSOTMjq1/rt+Rk8GVk808cbIq+3O/Z7/p2wD2ASd2gON/UonHWly9JYzPx3iV6slz5xaun7cBWoVXOIY4XFtISsWFmD+oqntTF5+54AEdKBLQk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
bot:
  automerge: true
